apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: web-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: web
    kind: Deployment
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "99"
    - type: prometheus
      metadata:
        serverAddress:  http://prom-stack-prometheus-server.kube-system.svc:80
        query: sum(rate(container_cpu_cfs_throttled_seconds_total{container!~'POD|', namespace='robot-shop', pod=~'web.*'}[5m]))
        threshold: "0.01"                  
  minReplicaCount: 1
  maxReplicaCount: 200
  pollingInterval:  120                               
  cooldownPeriod:   120 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cart-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: cart
    kind: Deployment
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
  minReplicaCount: 1
  maxReplicaCount: 200
  pollingInterval:  120                               
  cooldownPeriod:   120 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: catalogue-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: catalogue
    kind: Deployment
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
  minReplicaCount: 1
  maxReplicaCount: 200
  pollingInterval:  120                               
  cooldownPeriod:   120 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mongodb-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: mongodb
    kind: Deployment
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
  minReplicaCount: 1
  maxReplicaCount: 200
  pollingInterval:  120                               
  cooldownPeriod:   120 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mysql-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: mysql
    kind: Deployment
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
  minReplicaCount: 1
  maxReplicaCount: 400
  pollingInterval:  300                               
  cooldownPeriod:   300 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: dispatch-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: dispatch
    kind: Deployment
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "90"
  minReplicaCount: 1
  maxReplicaCount: 200
  pollingInterval:  120                               
  cooldownPeriod:   120 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: payment-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: payment
    kind: Deployment
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
  minReplicaCount: 1
  maxReplicaCount: 200
  pollingInterval:  120                               
  cooldownPeriod:   120 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ratings-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: ratings
    kind: Deployment
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
  minReplicaCount: 1
  maxReplicaCount: 200
  pollingInterval:  120                               
  cooldownPeriod:   120 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: shipping-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: shipping
    kind: Deployment
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
  minReplicaCount: 1
  maxReplicaCount: 200
  pollingInterval:  120                               
  cooldownPeriod:   120 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: user-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: user
    kind: Deployment
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
  minReplicaCount: 1
  maxReplicaCount: 200
  pollingInterval:  120                               
  cooldownPeriod:   120 
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-cpu-v0
  namespace: robot-shop
spec:
  scaleTargetRef:
    name: redis
    kind: statefulset
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "75"
  minReplicaCount: 1
  maxReplicaCount: 200
  pollingInterval:  30                               
  cooldownPeriod:   120