# Source: robot-shop/templates/load-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: load
  labels:
    service: load
spec:
  replicas: 2
  selector:
    matchLabels:
      service: load
  template:
    metadata:
      labels:
        service: load
    spec:
      containers:
      - name: load
        env:
          - name: HOST
            value: "http://web:8080/"
          - name: NUM_CLIENTS
            value: "10"
          - name: SILENT
            value: "1"
          - name: ERROR
            value: "0"
          - name: TRANSACTION_LOAD
            value: "0"
        image: saurabhjha1/rs-load:2.1.0-kubespray
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 500m
            memory: 1024Mi
