apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    service: catalogue
spec:
  replicas: 1
  selector:
    matchLabels:
      service: catalogue
  template:
    metadata:
      labels:
        service: catalogue
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      initContainers:
      - name: check-mongodb
        image: mongoclient/mongoclient:latest
        command:
        - sh
        - -c
        - |
          until mongo --host mongodb:27017 --eval "db = db.getSiblingDB('catalogue'); if (db.stats().ok == 0) { quit(1); }"; do
            echo 'waiting for mongodb'
            sleep 5
          done
      containers:
      - name: catalogue
        image: {{ .Values.image.repo }}/rs-catalogue:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: INSTANA_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 50m
            memory: 50Mi
        livenessProbe:
          exec:
            command:
            - sh
            - -c
            - 'curl http://localhost:8080/health | grep -q "{\"mongo\":true}"'
          initialDelaySeconds: 15
          periodSeconds: 10
          failureThreshold: 3
      restartPolicy: Always
      {{- with .Values.catalogue.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.catalogue.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.catalogue.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.secret }}
      {{- if .Values.secret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.secret.name }}
      {{- end }}
      {{- end }}
