apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    service: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  template:
    metadata:
      labels:
        service: web
    spec:
      {{ if .Values.psp.enabled }}
      serviceAccountName: robot-shop
      {{ end }}
      containers:
      - name: web
        image: {{ .Values.image.repo }}/rs-web:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        {{- if .Values.eum.key }}
        - name: INSTANA_EUM_KEY
          value: {{ .Values.eum.key }}
        - name: INSTANA_EUM_REPORTING_URL
          value: {{ .Values.eum.url }}
        {{- end}}
        {{- if .Values.instana.agent.host }}
        - name: INSTANA_AGENT_HOST
          value: {{ .Values.instana.agent.host }}
        {{- end}}
        {{- if .Values.instana.agent.port }}
        - name: INSTANA_AGENT_PORT
          value: "{{ .Values.instana.agent.port }}"
        {{- end}}
        - name: INSTANA_SERVICE_NAME
          value: nginx-web
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      restartPolicy: Always
      {{- with .Values.web.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.web.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.secret }}
      {{- if .Values.secret.enabled }}
      imagePullSecrets:
      - name: {{ .Values.secret.name }}
      {{- end }}
      {{- end }}